"""Harvest the "Example Input / Output" blocks from modern_robotics.core docstrings into
tests/mr_examples.py. Run once per MR release: `uv run python tools/harvest_mr_examples.py`.
"""

from __future__ import annotations

import inspect
import pathlib
import re

from modern_robotics import core

HEADER = '''"""Generated by tools/harvest_mr_examples.py from modern_robotics {version}. Do not edit.

Each entry is (MR function name, input block, output expression), the docstring's own
Example Input / Output, as Python source.
"""

MR_VERSION = {version!r}

EXAMPLES = [
'''


def harvest() -> list[tuple[str, str, str]]:
    out = []
    for name, fn in inspect.getmembers(core, inspect.isfunction):
        if fn.__module__ != core.__name__ or not fn.__doc__:
            continue
        doc = inspect.cleandoc(fn.__doc__)
        m = re.search(r"Example [Ii]nput.*?:\n(.*?)\n\s*Output:\n(.*)", doc, re.DOTALL)
        if not m:
            continue
        inp = inspect.cleandoc(m.group(1))
        outp = inspect.cleandoc(m.group(2).split("\n\n")[0])
        out.append((name, inp, outp))
    return sorted(out)


def main() -> None:
    import modern_robotics

    body = HEADER.format(version=modern_robotics.__version__)
    for name, inp, outp in harvest():
        body += f"    ({name!r},\n     {inp!r},\n     {outp!r}),\n"
    body += "]\n"
    target = pathlib.Path(__file__).resolve().parents[1] / "tests" / "mr_examples.py"
    target.write_text(body)
    print(f"wrote {len(harvest())} examples to {target}")


if __name__ == "__main__":
    main()
